
workflows:
  default-workflow:
    name: Build APK
    environment:
      flutter: stable
    scripts:
      - name: Ensure flutter project structure
        script: |
          if [ ! -d "android" ]; then
            echo "android folder missing — running flutter create . to generate platform folders"
            flutter create .
          else
            echo "android folder exists"
          fi
      - name: Get packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
