
workflows:
  default-workflow:
    name: Build APK
    environment:
      flutter: stable
    scripts:
      - name: Ensure flutter project structure (always run)
        script: |
          echo "Running flutter create . to ensure android/ exists and correct config"
          flutter create .
      - name: Get packages
        script: |
          flutter pub get
      - name: Build APK (release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
